[project]
name = "final-project"
version = "0.1.0"
description = "Final Project API"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.30",
    "fastapi>=0.115.0",
    "httpx>=0.28.1",
    "langchain>=1.2.6",
    "langchain-openai>=1.1.7",
    "langfuse>=3.12.0",
    "langgraph>=1.0.6",
    "mcp>=1.25.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
    "uvicorn>=0.30.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.4.0",
]
